### ISSUE TITLE
Release 2023 December

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1044]
## Timeline
To Processes-Test: 08.12.2023
To Processes-Hotfix, Processes-Demo, Prod: 15.12.2023

## TODOs

- [x] Prod-Change
- [x] Switch to new cocreation bpmn server #901
- [x] Bump dev branch version to next minor
- [x] DigiWF Forms neue Version ausbringen

**Comment by lmoesle** [comment]
Wir sollten auch [DigiWF Forms](https://git.muenchen.de/digitalisierung/digiwf-forms) aktualisieren und eine neue Version ausbringen.
Ich kann mir das am Montag anschauen (ich muss mir erst Nodejs auf dem LHM PC einrichten). Eine neue Version von DigiWF Forms auszubringen sollte dann ohne Downtime gehen.
