### ISSUE TITLE
Release 2024 January 2

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1176]
## Timeline
To Processes-Test: 19.01.2024
To Processes-Hotfix, Processes-Demo, Prod: 26.01.2024

## TODOs

- [x] Prod-Change
- [x] Bump dev branch version to next minor
- [x] Remove no-security for s3 and all correlating integrations #531 [digiwf-ops#325](https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/325)
- [x] BPM-Modeller ausbringen wegen  [BPM-Modeller!60](https://git.muenchen.de/digitalisierung/bpm-modeler/-/merge_requests/60)
- [x] KVR-DMS-EAI ausbringen mit neuer WSDL auf processes-Umgebungen
