### ISSUE TITLE
DigiWF Schulungs Umgebung

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1235]
Für Schulungen soll eine separate Umgebung ähnlich zu Processes-Test/Hotfix/Demo erstellt werden. Da die Umgebung rein für Schulungen genutzt werden kann, können alle deprecated Services (DMS, ...), Optimize und die meisten Integrationen entfernt werden. Die genauen Anforderungen sind in dem internen Ticket dokumentiert.
Als Datenbank soll eine PostgreSQL für Engine, Taskliste und S3 genutzt werden.

## TODOs
Siehe https://wiki.muenchen.de/betriebshandbuch/index.php?title=DigiWF&title=DigiWF&sfr=betriebshandbuch#Installationsdokumentation

- [x] Namspace in der CAP
- [x] PostgreSQL-DB für Engine, Tasklist, S3, BPM-Server
- [x] PostgreSQL-Schema Tasklist
- [x] PostgreSQL-Schema Engine
- [x] PostgreSQL-Schema S3
- [x] PostgreSQL-Schema BPM-Server
- [x] S3-Bucket für S3-Integration
- [x] Umgebung in digiwf-ops aufnehmen
- [ ] digiwf-ops mergen
- [x] Secrets anlegen
- [x] Config-Maps anlegen
- [x] digiwf Kafka-Topics erstellen/anpassen
- [x] cocreation Kafka-Topics erstellen/anpassen
- [x] SSO-Client konfigurieren cocreation-training
- [x] SSO-Client konfigurieren processestraining
- [x] Vanity-URLs
- [x] Camunda-Cockpit konfigurieren
- [x] CICD Token erstellen
- [x] image-puller konfigurieren digiwf-test, cocreation-test
- [x] SSL Fehler zum Kafka-Broker

## Akzeptanzkriterien

- [ ] Umgebung läuft mit allen benötigten Integrationen in der CAP
- [ ] Beispielprozess mit entsprechenden Integrationen läuft ohne Probleme (z.B. Feature S3 Integration)
- [ ] Deploy von CoCreation auf neue Umgebung funktioniert
- [ ] Cockpit ist aufrufbar für jeden und jeder sieht alle Prozesse und Instanzen

## Referenzen
- https://git.muenchen.de/digitalisierung/digiwf-support/-/issues/77

**Comment by simonhir** [comment]
@markostreich hab das einfach mal dir zugewiesen, das können wir uns dann gern zusammen anschauen. Die Doku sollte aber auf dem neusten Stand sein, weil ich die als ich die Hotfix-Umgebung erstellt habe aufgeräumt habe,

**Comment by markostreich** [comment]
@simonhir 

> Als Datenbank soll eine PostgreSQL für Engine, Taskliste und S3 genutzt werde.

Also abweichend vom Betriebshandbuch keine Oracle DB sondern **eine** PostgreSQL mit mehreren Schemata für drei Komponenten?

**Comment by simonhir** [comment]
@markostreich

ja da gibt es auch schon ein Ticket um alle anderen auf PostgreSQL umzustellen.

Beim Rest sollen es getrennte pro Service sein, da geht es eher drum einfach die Umgebung zurück setzten zu können für diesen Sonderfall.

**Comment by markostreich** [comment]
@simonhir bitte Review: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/355
