### ISSUE TITLE
Release Februar

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#1254]
## Timeline
To Processes-Test: 09.02.2024
To Processes-Hotfix, Processes-Demo, Prod: 16.02.2024

## TODOs

- [x] Prod-Change
- [ ] Bump dev branch version to next minor
- [x] Bpm Modeller neue Version ausbringen
- [x] StreamingTemplateV01 und StreamingTemplateV02 in allen Umgebungen aktualisieren
- [x] Formserver-Integration to 1.1.2 and test s3 auth see #531
- [x] Kustomize processestraining add features #881, #958, #1253
- [x] CoCreation wg. custom-dms-input ausbringen
- [x] Adress-Int. und DMS-Int. zweifach skalieren

**Comment by lmoesle** [comment]
Beim nächsten Release müssen die StreamingTemplates aktualisiert werden (in allen Umgebungen, in denen das Autodeployment deaktiviert ist). Das sind die neuen Templates: https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-engine/digiwf-engine-service/src/main/resources/bausteine/streaming (Ich kann leider keine .bpmn Dateien hochladen)
Deployed nach:
- [x] dev
- [x] test
- [x] demo
- [x] processestest
- [x] processesdemo
- [x] processeshotfix

**Comment by lmoesle** [comment]
Done - Ops PR für #958 https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/351

**Comment by lmoesle** [comment]
- [x] Element Templates für #958 https://git.muenchen.de/digitalisierung/bpm-modeler/-/merge_requests/63

**Comment by lmoesle** [comment]
Done - Ops PR für #1253 https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/356

**Comment by markostreich** [comment]
-[ ] Ops MR für Schulungsumgebung #1235: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/355
Muss passend zu Lukas' MRs gemacht werden.

**Comment by markostreich** [comment]
- [x] Ops MR für #881 https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/359

**Comment by lehju** [comment]
- [x] CoCreation ausbringen für #881 MR: https://github.com/it-at-m/digiwf-core/pull/1272

**Comment by lmoesle** [comment]
> Ops MR für Schulungsumgebung #1235: https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/355 Muss passend zu Lukas' MRs gemacht werden.

@markostreich FYI Ich habe meine MRs gemerged
