### ISSUE TITLE
Release 2024 March

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1357]
## Timeline
To Processes-Test: 01.03.2024
To Processes-Hotfix, Processes-Demo, Processes-Training, Prod: 08.03.2024

## TODOs

- [x] Prod-Change
- [x] Bump dev branch version to next minor
- Delete deprecated `Feature`-Processes (see #1355)
  - [x] Processes-Test
  - [x] Processes-Demo, -Hotfix, -Training
- [x] IntraP statt Intra auf Demo + Processes + CoCreation-Demo #1403
- [x] no-reply@muenchen.de als Absender in Engine und Email-Int [intern#381](https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/381)
- [x] Ops-MR für Entfernen AppD #658 [digiwf-ops#399](https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/399), needs #1426 in release

**Comment by lehju** [comment]
- [ ] Ops MR für #1227 https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/392
- [ ] Umbenennung Secret digiwf-dmskvr-basic-auth zu digiwf-alwdms-basic-auth
