### ISSUE TITLE
Release 2024 March 2

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1431]
## Timeline
To Processes-Test: 22.03.2024
To Processes-Hotfix, Processes-Demo, Processes-Training, Prod: vrmtl. 05.04.2024, as 29.03.2024 is public holiday

## TODOs

- [x] Prod-Change: [CHG0187612](https://it-services.muenchen.de/change_request.do?sys_id=578215101bd1ce50891654a36b4bcbab)
- [x] Bump dev branch version to next minor
- [x] Cleanup `digiwf-dms-integration` after rename to `digiwf-mucs-dms-integration`
- [x] Use digiwf-forms-service 1.4.0 or higher
- [x] Release bpm-modeler for #1444 and #1277

**Comment by lehju** [comment]
ALW-DMS-Integration #1227:
- [x] Ops MR https://git.muenchen.de/digitalisierung/digiwf-ops/-/merge_requests/392
- [x] Umbenennung Secret digiwf-dmskvr-basic-auth zu digiwf-alwdms-basic-auth (ist angelegt; altes Secret muss jeweils noch gelöscht werden)
- [x] BPM-Modeler MR https://git.muenchen.de/digitalisierung/bpm-modeler/-/merge_requests/74

**Comment by lehju** [comment]
Bilder und Links in Mails:
- [x] BPM-Modeler MR für #1277 https://git.muenchen.de/digitalisierung/bpm-modeler/-/merge_requests/73

**Comment by darenegade** [comment]
@markostreich 

Kann die dms-integration gelöscht werden auf allen Umgebungen?

**Comment by markostreich** [comment]
Wegen dem hier bin ich mir nun auch nicht mehr sicher:
https://git.muenchen.de/digitalisierung/bpm-modeler/-/commit/e66aa9fa1f2e540780775063661e43f159deb5e5

@lehju kannst du das aufklären? :-)
