### ISSUE TITLE
Release 2024 April

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1544]
## Timeline
To Processes-Test: 16.04.2024
To Processes-Hotfix, Processes-Demo, Processes-Training, Prod: 26.04.2024

## TODOs

- [x] Prod-Change CHG0192246
- [x] Bump dev branch version to next minor
- [x] Release bpm-modeler with [bpm-modeler!78](https://git.muenchen.de/digitalisierung/bpm-modeler/-/merge_requests/78) for ticket-integration-templates
- [x] #1251 bzw. #1527 ausrollen und Temp.-Umsetzung aufräumen - ~~Eventuell manuelle Flyway Migration notwendig~~ (Environment-Variablen kontrollieren)
- [x] BPM-Modeler für #1548 ausbringen
- [x] ES auf Prod update - See #1569 
- [x] Certbot für ES auf Prod installieren #1506

**Comment by markostreich** [comment]
Ausrollen wurde verschoben. Daten sind angepasst.
