### ISSUE TITLE
Release 2024 Mai

### ISSUE THREAD

**Issue by darenegade** [it-at-m/digiwf-core#1605]
## Timeline
To Processes-Test: 03.05.2024
To Processes-Hotfix, Processes-Demo, Processes-Training, Prod: 10.05.2024

## TODOs

- [x] Prod-Change
- [x] Bump dev branch version to next minor
- [x] Release and deploy WebComp from #1570 and [digiwf-ops!429](https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/429)
- [ ] Release and deploy OAuth2 for Optimize #808 and [digiwf-ops!432](https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/432)
- [x] Release BPM-Modeler for [bpm-modeler!81](https://git.muenchen.de/digitalisierung/digiwf/bpm-modeler/-/merge_requests/81) and [bpm-modeler!82](https://git.muenchen.de/digitalisierung/digiwf/bpm-modeler/-/merge_requests/82)

**Comment by devtobi** [comment]
## TODOs
- [ ] Infrastruktur ausrollen (https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/429)

**Comment by darenegade** [comment]
@markostreich @simonhir 

Kann ich einen Release vom BPM-Modeller noch dazwischen schieben? Hab das noch gefunden und das löst direkt ein Ticket in Support:

https://git.muenchen.de/digitalisierung/digiwf/bpm-modeler/-/merge_requests/82
