### ISSUE TITLE
Release 2024 Mai 2

### ISSUE THREAD

**Issue by markostreich** [it-at-m/digiwf-core#1686]
## Timeline
To Processes-Test: 24.05.2024
To Processes-Hotfix, Processes-Demo, Processes-Training, Prod: 31.05.2024

## TODOs

- [x] Prod-Change: [CHG0202746](https://it-services.muenchen.de/now/nav/ui/classic/params/target/change_request.do%3Fsys_id%3Dafd5a72a1b9e02dc673e859c7b4bcb20)
- [x] Bump dev branch version to next minor
- [x] Release and deploy WebComp from #1682 and [digiwf-ops!446](https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/446)
- [x] Release and deploy OAuth2 for Optimize #808 and [digiwf-ops!432](https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/432)
  - [Backup](https://docs.camunda.io/docs/self-managed/operational-guides/backup-restore/optimize-backup/) and upgrade Optimize from 3.8 rolling to 3.11 (3.11->3.12 is done with new image)
    - [x] Demo
    - [x] Processes-Test
    - [x] Processes-Demo
    - [x] Prod
  - [x] Delete old optimize routes
- [x] Release and deploy [DigiWF Forms](https://git.muenchen.de/digitalisierung/digiwf/digiwf-forms/-/merge_requests/83) for #1494 
~~- [ ] Release and deploy S3 Client lib #1442 and [digiwf!ops!447](https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/447)~~
