### ISSUE TITLE
Release 2024 Juni

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1753]
## Timeline
To Processes-Test: 14.06.2024
To Processes-Hotfix, Processes-Demo, Processes-Training, Prod: 21.06.2024

## TODOs

- [x] Prod-Change CHG0207492
- [x] Bump dev branch version to next minor
- [x] Release/merge [digiwf-ops!447](https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/447) for #1442
- [x] Release BPM-Modeler with [digiwf/bpm-modeler!86](https://git.muenchen.de/digitalisierung/digiwf/bpm-modeler/-/merge_requests/86) for #1671
- [x] Abschaltung lasttest, processeshotfix, training #1757
