### ISSUE TITLE
Release 2024 Juli

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#1765]
## Timeline
To Processes-Test: 26.07.2024
To Processes-Demo, Prod: 02.08.2024

## TODOs

- [x] Prod-Change CHG0223024
- [ ] Bump dev branch version to next minor
- [x] Release BPM-Modeler with [bpm-modeler!87](https://git.muenchen.de/digitalisierung/digiwf/bpm-modeler/-/merge_requests/87) for #1704 and [bpm-modeler!93](https://git.muenchen.de/digitalisierung/digiwf/bpm-modeler/-/merge_requests/93) for #1734
- [x] Release Forms with [86](https://git.muenchen.de/digitalisierung/digiwf/digiwf-forms/-/merge_requests/86) for #1699
- [ ] Rollout gateway with downtime for hazelcast upgrade from #1536 and #1822
- [x] Update ops-repo with MR [470](https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/470) for properties refactoring in #1706 and [digiwf-ops!472](https://git.muenchen.de/digitalisierung/digiwf/digiwf-ops/-/merge_requests/472) for #1264 (rm s3 db)
- [ ] Upgrade Optimize  from 3.12.0 to 3.13.0 with `./upgrade/upgrade.sh` for #1536
