### ISSUE TITLE
Simplify release pipeline

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#518]
**Tasks**

- Split the release pipelines of apps and services into 2-3 workflows
- Include 2 workflows into a single release pipe: [Actions ReUse](https://docs.github.com/en/actions/using-workflows/reusing-workflows)
- Version Bump of Apps and Services into one Action and one git push
- Use the [ccse template](https://git.muenchen.de/ccse/open-source-strategie-ccse/open-source-aktivitaeten/-/wikis/Maven-Central) for the java/mvn release pipeline and extend it with docker builds
- Fix if two builds run parallel i.e. for `pull_request` and `push` on a mr or in the release pipeline one fails while engine tests

**Additional context**

- See: https://github.com/it-at-m/digiwf-project/issues/501#issuecomment-1591014921

**Criteria**

- [ ] The release pipelines of apps and services should be split into 2 workflows: one for apps and one for services.
- [ ] The ccse template for the java/mvn release pipeline should be used.
- [ ] The java/mvn release pipeline should be extended with docker builds.
- [ ] The pipeline doesn't fail when two engine builds are running in parallel

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/518?planning-poker) with Zenhub @darenegade @lehju @simonhir @StephanStrehlerCGI

**Comment by darenegade** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/518?planning-poker) with Zenhub @AnHo314

**Comment by lmoesle** [comment]
Wegen der Branch Protection (https://github.com/orgs/community/discussions/25305#discussioncomment-3247401) soll für den Version Bump (analog zu Dependabot) ein PR auf den dev Branch aufgemacht werden

**Comment by lmoesle** [comment]
Der Java Release muss noch refactored werden (Stichwort CCSE Template)

**Comment by darenegade** [comment]
Waits for #635
