### ISSUE TITLE
Migrate digiwf-engine to Spring Boot 3

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#762]
Migrate digiwf-gateway to Spring Boot 3 (see [Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide)).

**Todo**

- Follow: https://github.com/holunda-io/polyflow-examples/issues/233
- Upgrade Spring Boot
- Upgrade Spring Security
- Configure Properties
	- Use the spring-boot-properties-migrator module to detect props that changed
- Rename `spring.factories` to `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`
- Upgrade Dependencies

**Acceptance Criteria**

- [ ] Engine ist auf SB3 gehoben
- [ ] Testprozesse laufen durch (Testkonzept)
- [ ] Alte Forms laufen noch ("DigiWF erleben" läuft noch)
- [ ] Legacy-Integrationen funktionieren (DMS KVR/MUCS)
- [ ] Cockpit funktioniert noch (Login und Prozesse laden usw.)
- [ ] I-Test (digiwf-tasklist-itest) ist wieder aktiv und funktioniert

**Additional Context**

- https://github.com/holunda-io/polyflow-examples/issues/233#issuecomment-1755538639
- Remove `@ConstructionBinding` https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#constructingbinding-no-longer-needed-at-the-type-level 
- REST Template https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#apache-httpclient-in-resttemplate
- Flyway https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#flyway
- Hibernate https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#hibernate-61

**Comment by lmoesle** [comment]
FYI Mit Spring Cloud 2022.0.4 hat sich das Funktion Routing geändert (https://github.com/it-at-m/digiwf-core/pull/892#issuecomment-1781268535).
