### ISSUE TITLE
Migrate digiwf-integrations to Spring Boot 3

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#768]
Migrate digiwf-integrations to Spring Boot 3 (see [Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide)).

**Todo**

- Upgrade Spring Boot
- Upgrade Spring Security
- Configure Properties
	- Use the spring-boot-properties-migrator module to detect props that changed
- Rename `spring.factories` to `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`
- Upgrade Dependencies
- Open a PR for each integration
- Ignore Legacy Integrations

Integrations: 
- [x] address integration --> Stephan
- [x] alw integration --> Stephan
- [x] cosys integration --> Julia
- [x] dms integration --> Julia
- [x] email integration --> Julia
- [x] example integration --> Stephan
- [ ] okewo-integration  --> Stephan
- [x] s3-integration --> Simon Z
- [x] verification integration remove from repo --> Stephan

**Additional Context**

- REST Template https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#apache-httpclient-in-resttemplate
- Flyway https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#flyway

**Comment by darenegade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/768?planning-poker) with Zenhub @darenegade @dominikhorn93 @lehju @StephanStrehlerCGI

**Comment by darenegade** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DigiWF-621f70bf50ea1100120b7e93/issues/it-at-m/digiwf-core/768?planning-poker) with Zenhub @zambrovski

**Comment by lmoesle** [comment]
Das Function Routing hat sich mit Spring Cloud 2022.0.4 geändert. Dementsprechend hat sich auch die digiwf-message lib geändert und es muss die application.yml angepasst werden. https://github.com/it-at-m/digiwf-core/pull/892#issuecomment-1781268535

**Comment by StephanStrehlerCGI** [comment]
Address Integration: Überprüfung Parameter Codierung: v2/adresse/check?adresse=Agnes-Pockels-Bogen%2021%2C%2080992%20M%C3%BCnchen

"Neue Kodierung" klappt auch bei Address service. tests werden angepasst: https://address-service-test.muenchen.de/v2/adresse/check?adresse=Agnes-Pockels-Bogen%2021%2C%2080992%20M%C3%BCnchen
