### ISSUE TITLE
Refactor Formserver Integration

### ISSUE THREAD

**Issue by lmoesle** [it-at-m/digiwf-core#794]
**Is your feature request related to a problem? Please describe.**

The formserver integration (https://git.muenchen.de/digitalisierung/digiwf-formserver-integration) is in bad shape:
- uses old dependencies
- the code is very hard to understand due to spaghetti code and complex side effects
- very few tests and lots of untested code
- you have to hack new features into the code base to avoid major rewrites of the entire integration (e.g. https://git.muenchen.de/digitalisierung/digiwf-formserver-integration/-/merge_requests/11)

**Describe the solution you'd like**

I suggest to migrate the formserver integration to our digiwf-core monorepo (github) by rewriting the integration (similar to our new digiwf-dms-integration).

```[tasklist]
### Tasks
- [ ] Check the current codebase and document the existing usecases
- [ ] Setup a digiwf-formserver-integration module in the monorepo and implement a basic integration (hexagonal structure)
- [ ] Implement existing usecases
- [ ] Create a createFile port using the S3 Integration Client and the digiwf-process-api (processconfig)
- [ ] Use the digiwf-message lib to start processes
- [ ] Use digiwf-spring-secruity lib to implement spring security
- [ ] Setup a dockerfile and adjust the build pipeline to release a docker image to dockerhub
```
