### ISSUE TITLE
Release 2023 November

### ISSUE THREAD

**Issue by simonhir** [it-at-m/digiwf-core#957]
## Timeline
To Processes-Test: 17.11.2023
To Processes-Hotfix, Processes-Demo, Prod: 24.11.2023

## TODOs

- [x] Prod-Change: CHG0153566
- [x] Release eai-mucdms to Prod on 17.11.2023 #595
- [x] Release bpm-modeler

**Comment by darenegade** [comment]
@simonhir Für die GraalVM müssen wir noch den Nashorn-Compat aktivieren

https://www.graalvm.org/latest/reference-manual/js/NashornMigrationGuide/#nashorn-compatibility-mode
